Stage-1: added 'words.txt' file, printed lines from the file
hassantillkassan/LearnEnglishWordsTelegramBot pull request #1
Opened 2024-04-09 19:54 UTC by hassantillkassan

2024-04-09 22:54 UTC, danelyan requested changes
Привет! Поздравляю со стартом курсовой )
По всем вопросам можешь писать прямо в комментарии к пул-реквестами или [в любое время мне в личку](https://t.me/fridonium) по любым вопросам.

Смотри коммент ниже )

2024-04-09 22:54 UTC, danelyan commented on src/main/kotlin/words.txt
> +hello привет
этот файл лучше положить в корень проекта и открывать по адресу "words.txt".
В будущем когда приложение будет публиковаться на сервер в виде jar-файла, так будет проще редактировать и пополнять словарь (без пересборки проекта)

2024-04-10 12:53 UTC, hassantillkassan commented
Привет! Приятно познакомиться) Сразу вопрос, есть ли стиль оформления коммитов и правила нейминга веток? Например, в ходе KotlinSprint под задачи мы создавали ветку с названием KS-<номер урока>-<номер задачи> и далее уже само название задачи

2024-04-11 07:44 UTC, danelyan approved these changes
> Привет! Приятно познакомиться) Сразу вопрос, есть ли стиль оформления коммитов и правила нейминга веток? Например, в ходе KotlinSprint под задачи мы создавали ветку с названием KS-<номер урока>-<номер задачи> и далее уже само название задачи

А ты хорош ))
Давай придерживаться заданного тобой формата `Stage-N-<task name>`
И для коммитов/названий пуллреквестов формата `Stage-N: <message>`

2024-04-11 19:37 UTC, merged