Stage-4: word learning functionality in first when-branch, added func…
hassantillkassan/LearnEnglishWordsTelegramBot pull request #4
Opened 2024-04-18 19:26 UTC by hassantillkassan

…tions 'updateCorrectAnswersCount' and 'updateVocabulary'

2024-04-19 06:55 UTC, danelyan requested changes

2024-04-19 06:55 UTC, danelyan commented on src/main/kotlin/Menu.kt
> +                    if (listOfUnlearnedWords.isEmpty()) break
Давай напишем, что все слова выучены

2024-04-19 06:55 UTC, danelyan commented on src/main/kotlin/Menu.kt
> +                    val answers = listOfUnlearnedWords.shuffled().take(4)
4 - в константы

2024-04-19 06:55 UTC, danelyan commented on src/main/kotlin/Menu.kt
> +                    val question = answers.random().text
не обязательно доставать тут text, можешь использовать ниже экземпляр класса Word, и уже при печати доставать из него нужные поля. Так будет гибче.
И давай переименуем, correctAnswer лучше подходит

2024-04-19 18:35 UTC, hassantillkassan commented
Исправил. А как в целом код функционала изучения слов? Не слишком ли "тяжёлый"? А то мы столько переменных создаём при каждой итерации цикла, перебираем списки...

2024-04-21 06:38 UTC, danelyan requested changes
> А как в целом код функционала изучения слов? Не слишком ли "тяжёлый"? А то мы столько переменных создаём при каждой итерации цикла, перебираем списки...

Что касается переменных, не страшно. Они локальные, с небольшой областью видимости. Garbage Collector их сразу собирает. А со списками - допустимо тяжелый. Но ты прав, нужно всегда понимать что происходит у тебя "под капотом" твоих функций. К примеру filter осуществляет пробег по всему списку и создает новый список. Как и map

2024-04-21 06:38 UTC, danelyan commented on src/main/kotlin/Menu.kt
> +                    val answers = listOfUnlearnedWords.shuffled().take(NUM_OF_CHOICES)
Не учтен случай, когда невыученных слов меньше NUM_OF_CHOICES. Будет показано всего 3 (2 или 1) вариант для ответа. В случае 1 будет выглядеть нелепо ).

Давай если вариантов меньше NUM_OF_CHOICES, формировать список выученных слов, оттуда выбирать NUM_OF_CHOICES - answers.size и дополнять список, перемешивая

2024-04-21 06:38 UTC, danelyan commented on src/main/kotlin/Menu.kt
> +                            updateCorrectAnswersCount(vocabulary, correctAnswer.text)
тут можно проще:
```Kotlin
correctAnswer.correctAnswersCount++
```
Потому что vocabulary - это список ссылок Word, а correctAnswer хранит ссылку на Word в vocabulary. То есть - все слова после загрузки из файла хранятся в так называемой "Куче", 

А метод updateCorrectAnswersCount() нам не нужен в целом.
И еще давай вызывать updateVocabulary(vocabulary) сразу после `correctAnswer.correctAnswersCount++`, чтобы если приложение вдруг упадет или сервер перезагрузится - данные не потерялись

2024-04-21 06:38 UTC, danelyan commented on src/main/kotlin/Vocabulary.kt
> +fun updateCorrectAnswersCount(vocabulary: MutableList<Word>, wordToUpdate: String) {
этот метод не нужен

2024-04-21 06:38 UTC, danelyan commented on src/main/kotlin/Vocabulary.kt
> +    val content = vocabulary.joinToString("\n") { "${it.text}|${it.translate}|${it.correctAnswersCount}" }
Это не критично для нашего бота, но в будущем так лучше не делать.
В Kotlin есть [ограничения на размер строки](https://stackoverflow.com/a/62099087) в 65 килобайт. Лучше писать в файл построчно

2024-04-21 16:59 UTC, hassantillkassan commented
Файл Menu.kt, 37-я строка. Почему я сделал такое мудрёное сложение сложение коллекций. Потому, в таком виде
```
answers+= learnedWords
answers.shuffled()
```
варианты ответов как-то странно перемешивались. К примеру, если у нас осталось два невыученных слова, то среди вариантов ответа в консоли всегда первыми двумя отображались переводы двух невыученных слов, и только потом к ним добавлялись случайные из выученных.
Сейчас все работает нормально, потестил раз 10

2024-04-21 18:38 UTC, danelyan approved these changes
Идеально )

2024-04-22 11:26 UTC, merged