Stage-6: refactored the code, fixed bugs
hassantillkassan/LearnEnglishWordsTelegramBot pull request #6
Opened 2024-04-28 17:46 UTC by hassantillkassan

2024-04-28 17:48 UTC, hassantillkassan commented
Появился конфликт в ветке. Такое впервые
![image](https://github.com/hassantillkassan/LearnEnglishWordsTelegramBot/assets/52125620/66e8bfe8-2802-4b82-8ea6-44b3e9f0559b)

2024-05-04 11:05 UTC, danelyan requested changes

2024-05-04 11:05 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +     private fun loadVocabulary(): MutableList<Word> {
Тут можно возвращать List<Word>. И в целом, там где возможно, давай обходится максимально абстрактным классом.
Например в данном случае ты как бы явно говоришь "список слов возвращаемый методом loadVocabulary() нельзя менять". Код который хорошо ограничен по возможностям, более стоек к ошибкам

2024-05-04 11:05 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +    val vocabulary = loadVocabulary()
Поле лучше сделать приватным. Это называется инкапсуляция - когда ты скрываешь детали реализации. Полезно придерживаться подобного подхода, чтобы снижать связанность между классами. Чем меньше классы знают друг о друге, тем лучше.

К примеру, ты захочешь хранить словарь не в List<Word>, а например в Map<String, Word> или вообще где-то в базе данных. Если поле приватное, можно не беспокоиться, что кто-то им воспользуется извне.

2024-05-04 11:05 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +     private fun updateVocabulary(vocabulary: MutableList<Word>) {
тут тоже достаточно просто List<Word>

2024-05-04 11:05 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        File("words.txt").writeText(content)
Можно вынести words.txt в конструктор класса LearnWordsTrainer

2024-05-04 11:05 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +            .filter { it.correctAnswersCount < SUCCESSFUL_NUM_OF_TIMES }
Константы NUM_OF_CHOICES и SUCCESSFUL_NUM_OF_TIMES можно вынести в конструктор класса LearnWordsTrainer. Тогда у тебя появится возможность в будущем динамически менять эти параметры без перекомпиляции кода

2024-05-13 12:03 UTC, danelyan approved these changes
Хорошо

2024-08-05 19:50 UTC, merged